### ISSUE TITLE
Bowden stl files missing

### ISSUE THREAD

**Issue by drross** [cookiengineer/anet-a8-upgrades#2]
Can you reupload the files for the bowden motor block and pneumatic adapter? I've already printed the mount and button. Thank you for the awesome write up!

**Comment by cookiengineer** [comment]
You can reuse the motor block parts from the OEM Anet. The bowden upgrade only requires these parts:

- The tube feed side aka motor block (because the other one stays on the carriage)
- The motor block mount
- The bowden adapter aka pneumatic adapter (tube feed opposite), which is screwed inside the previously used motor extrusion side.

All parts are in here, the button is obviously optional :)

https://github.com/cookiengineer/anet-a8-upgrades/tree/master/parts/bowden-extruder

Let me know if that cleared things up for you.

**Comment by cookiengineer** [comment]
Take this picture:

- motor block mount is yellow
- motor block part is grey
- OEM (metal part) is black

https://github.com/cookiengineer/anet-a8-upgrades/blob/master/photos/bowden-motor.jpg
